/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luis' at '9/28/16 11:16 PM' with Gradle 3.0
 *
 * @author luis, @date 9/28/16 11:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
